import Head from "next/head";
import {NavBar} from "@/components/navbar";
import {Button} from "@/components/ui/button"

export default function Home({csrfToken}: { csrfToken: string }) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app"/>
				<meta name="viewport" content="width=device-width, initial-scale=1"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>
			<main>
				<NavBar/>
				<Button>test</Button>
				<button className={"bg-blue-300 p-10"}>test</button>
			</main>
		</>
	);
}



