import {useState, useRef, useEffect} from "react";
import Image from 'next/image';
import Head from "next/head";
import {Cardo, Outfit} from "@next/font/google";

import styles from "@/styles/pages/landing.module.scss"

import {MenuButton} from "@/components/button/landing"
import {Button} from "@/components/button";
import OverText from "@/components/display/landing/overtext";
import OverMenu from "@/components/display/landing/overlaymenu";

import {AiOutlineSearch} from "react-icons/ai";

import image1 from "@./public/landing/image1.jpg"
import image2 from "@./public/landing/image2.jpg"
import image3 from "@./public/landing/image3.jpg"
import image4 from "@./public/landing/image4.jpg"
import image5 from "@./public/landing/image5.jpg"
import {Contact} from "@/components/display/landing/contact";

const outfit = Outfit({weight: "400", style: "normal", subsets: ["latin"]})
const cardo = Cardo({weight: "400", style: "italic", subsets: ["latin", "greek"]})

export default function Home() {
	const searchInputRef = useRef<HTMLInputElement>(null)
	const [search, setSearch] = useState(false)

	const colorList = [
		{set1: "#DC6A74", set2: "#D61C4E"},
		{set1: "#4E4B90", set2: "#50AB75"},
		{set1: "#AC001A", set2: "#FAC213"}
	]
	const timePerLoop = 10000

	const [state, setState] = useState<number>(0);
	const [overMenu, setOverMenu] = useState(false)
	const [contact, setContact] = useState(false)
	const [seed, setSeed] = useState(false)
	const [color, setColor] = useState(false)
	const [type, setType] = useState(false)
	const [season, setSeason] = useState(false)
	const [recommend, setRecommend] = useState(false)


	useEffect(() => {
		console.log(state)

		function intervalCallback() {
			if (state < colorList.length - 1) {
				setState((prev) => prev + 1)
			} else {
				setState(0)
			}
		}

		const interval = setInterval(intervalCallback, timePerLoop)
		return () => clearInterval(interval)
	}, [colorList.length, state])
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>
			<main style={{position: "relative"}}>
				<div className={styles.main + " " + cardo.className}>
					<div className={styles.sidebar + " " + styles.leftsidebar}>
						<MenuButton onClick={() => setOverMenu(true)}>All Flower Seeds</MenuButton>
						<MenuButton onClick={() => setOverMenu(true)}>Flower Color</MenuButton>
						<MenuButton onClick={() => setOverMenu(true)}>Flower Type</MenuButton>
						<MenuButton onClick={() => setOverMenu(true)}>Blooming Season</MenuButton>
						<MenuButton onClick={() => setOverMenu(true)}>Highly Recommended</MenuButton>
						<MenuButton
							onClick={() => {
								setContact(true)
								setOverMenu(true)
							}}
						>Contact</MenuButton>
					</div>
					<div className={styles.rightContent}>
						<div className={styles.content}>
							<div
								className={styles.imageContainer}
								style={{opacity: state == 0 ? 1 : 0}}
							>
								<div className={styles.image}>
									<Image
										className={styles.only}
										src={image1}
										alt={""}
										sizes={"9000px"}
									/>
								</div>
							</div>
							<div
								className={styles.imageContainer}
								style={{opacity: state == 1 ? 1 : 0}}
							>
								<div
									className={styles.image}
									style={{paddingBottom: "3rem"}}
								>
									<Image
										className={styles.image1}
										src={image2}
										alt={""}
										sizes={"9000px"}
									/>
									<Image
										className={styles.image2}
										src={image3}
										alt={""}
										sizes={"9000px"}
									/>
								</div>
							</div>
							<div
								className={styles.imageContainer}
								style={{opacity: state == 2 ? 1 : 0}}
							>
								<div
									className={styles.image}
									style={{paddingBottom: "3rem"}}
								>
									<div style={{justifyContent: "start", alignItems: "start"}}>
										<Image
											className={styles.image3}
											src={image4}
											alt={""}
											sizes={"9000px"}
										/>
									</div>
									<div style={{justifyContent: "end", alignItems: "end"}}>
										<Image
											className={styles.image4}
											src={image5}
											alt={""}
											sizes={"9000px"}
										/>
									</div>
								</div>
							</div>
						</div>
						<div className={`${styles.sidebar} ${styles.rightsidebar}`}>
							<div>
								<div className={`${styles.searchMenu} ${search || !!searchInputRef.current?.value ? styles.searchActive : ''}`}>
									<div className={outfit.className}>
										<input
											ref={searchInputRef}
											style={{width: search || !!searchInputRef.current?.value ? "100%" : "0",}}
											type={"search"}
											placeholder={"What are you looking for ?"}
											onMouseOver={() => setSearch(true)}
											onMouseLeave={() => setSearch(false)}
										/>
									</div>
									<div
										onMouseOver={() => setSearch(true)}
										onMouseLeave={() => setSearch(false)}
									>
										<AiOutlineSearch size={"25"}/>
									</div>
								</div>
							</div>
							<div><Button>log in</Button></div>
						</div>
					</div>
					<OverText
						colors={colorList}
						content={{set1: "The Vivid", set2: "Blossom"}}
						timePerLoop={8000}
						state={state}
					/>
				</div>
				<OverMenu
					onClose={() => {
						setOverMenu(false)
						setContact(false)
						setSeed(false)
						setColor(false)
						setType(false)
						setSeason(false)
						setRecommend(false)
					}}
					style={overMenu ? {opacity: "0.9", zIndex: 3} : {opacity: "0", zIndex: 0}}
				>
					{seed && ""}
					{color && ""}
					{type && ""}
					{season && ""}
					{recommend && ""}
					{contact && <Contact/>}
				</OverMenu>
			</main>

		</>
	)
		;
}